/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crud;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ryan Dave
 */
public class NewJFrame extends javax.swing.JFrame {
    private DefaultTableModel model;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

    initComponents();

    model = (DefaultTableModel) tblEmployees.getModel();

    loadEmployees();

    tblEmployees.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {

            int row = tblEmployees.getSelectedRow();

            if (row >= 0) {

                txtID.setText(
                    tblEmployees.getValueAt(row, 0).toString()
                );

                txtName.setText(
                    tblEmployees.getValueAt(row, 1).toString()
                );

                cmbDepartment.setSelectedItem(
                    tblEmployees.getValueAt(row, 2).toString()
                );

                txtPosition.setText(
                    tblEmployees.getValueAt(row, 3).toString()
                );

                txtSalary.setText(
                    tblEmployees.getValueAt(row, 4).toString()
                );
            }
        }
    });
}

    private void clearFields() {

    txtID.setText("");
    txtName.setText("");
    txtPosition.setText("");
    txtSalary.setText("");

    if (cmbDepartment.getItemCount() > 0) {
        cmbDepartment.setSelectedIndex(0);
    }

    txtSearch.setText("");

    tblEmployees.clearSelection();
}

  private void loadEmployees() {

    DefaultTableModel model =
        (DefaultTableModel) tblEmployees.getModel();

    model.setRowCount(0);

    String sql =
        "SELECT [ID], [Name], [Department], [Position], [Salary] " +
        "FROM [Employees]";

    try {

        Connection con = MSConnect.conn();

        if (con == null) {
            return;
        }

        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("ID"),
                rs.getString("Name"),
                rs.getString("Department"),
                rs.getString("Position"),
                rs.getDouble("Salary")
            });
        }

        rs.close();
        st.close();
        con.close();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error loading records:\n" + e.getMessage()
        );
    }
}







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE MANAGEMENT SYSTEM  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee ID :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Department:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel2.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, 30));
        jPanel2.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Salary:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText(" EMPLOYEE DETAILS ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 70, 30));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 70, 30));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 70, 30));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Full Name:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " IT  ", "HR  ", "Finance " }));
        jPanel2.add(cmbDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, 30));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 500));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 30));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 30));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("EMPLOYEE RECORDS ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Search:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 30));

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 80, 30));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "DEPARTMENT", "POSITION", "SALARY  "
            }
        ));
        tblEmployees.setName(""); // NOI18N
        jScrollPane1.setViewportView(tblEmployees);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 310));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 380, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       // Get values from the form
    String idText = txtID.getText().trim();
    String name = txtName.getText().trim();
    String department = cmbDepartment.getSelectedItem().toString();
    String position = txtPosition.getText().trim();
    String salaryText = txtSalary.getText().trim();

    // Check required fields
    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter Employee ID."
        );
        txtID.requestFocus();
        return;
    }

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter Full Name."
        );
        txtName.requestFocus();
        return;
    }

    if (position.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter Position."
        );
        txtPosition.requestFocus();
        return;
    }

    if (salaryText.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter Salary."
        );
        txtSalary.requestFocus();
        return;
    }

    try {

        int id = Integer.parseInt(idText);
        double salary = Double.parseDouble(salaryText);

        String sql =
            "INSERT INTO Employees " +
            "([ID], [Name], [Department], [Position], [Salary]) " +
            "VALUES (?, ?, ?, ?, ?)";

        try (
            Connection con = MSConnect.conn();
            PreparedStatement pst = con.prepareStatement(sql)
        ) {

            if (con == null) {
                return;
            }

            pst.setInt(1, id);
            pst.setString(2, name);
            pst.setString(3, department);
            pst.setString(4, position);
            pst.setDouble(5, salary);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(
                this,
                "Employee Added Successfully!"
            );

            loadEmployees();

            // Clear fields
            txtID.setText("");
            txtName.setText("");
            cmbDepartment.setSelectedIndex(0);
            txtPosition.setText("");
            txtSalary.setText("");

        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
            this,
            "Employee ID and Salary must be numbers."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Database Error:\n" + e.getMessage()
        );
    }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      String idText = txtID.getText().trim();
    String name = txtName.getText().trim();
    String department = cmbDepartment.getSelectedItem().toString();
    String position = txtPosition.getText().trim();
    String salaryText = txtSalary.getText().trim();

    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter Employee ID."
        );
        txtID.requestFocus();
        return;
    }

    if (name.isEmpty() || position.isEmpty() || salaryText.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please complete all employee details."
        );
        return;
    }

    try {

        int id = Integer.parseInt(idText);
        double salary = Double.parseDouble(salaryText);

        String sql =
            "UPDATE Employees SET " +
            "[Name] = ?, " +
            "[Department] = ?, " +
            "[Position] = ?, " +
            "[Salary] = ? " +
            "WHERE [ID] = ?";

        try (
            Connection con = MSConnect.conn();
            PreparedStatement pst = con.prepareStatement(sql)
        ) {

            if (con == null) {
                return;
            }

            pst.setString(1, name);
            pst.setString(2, department);
            pst.setString(3, position);
            pst.setDouble(4, salary);
            pst.setInt(5, id);

            int rows = pst.executeUpdate();

            if (rows > 0) {

                JOptionPane.showMessageDialog(
                    this,
                    "Employee Updated Successfully!"
                );

                loadEmployees();

            } else {

                JOptionPane.showMessageDialog(
                    this,
                    "Employee ID " + id + " was not found."
                );
            }
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
            this,
            "Employee ID and Salary must be numbers."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Database Error:\n" + e.getMessage()
        );
    }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      
  String idText = txtID.getText().trim();

    if (idText.isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Please enter Employee ID to delete."
        );

        txtID.requestFocus();
        return;
    }

    try {

        int id = Integer.parseInt(idText);

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete Employee ID " + id + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql =
            "DELETE FROM Employees WHERE [ID] = ?";

        try (
            Connection con = MSConnect.conn();
            PreparedStatement pst = con.prepareStatement(sql)
        ) {

            if (con == null) {
                return;
            }

            pst.setInt(1, id);

            int rows = pst.executeUpdate();

            if (rows > 0) {

                JOptionPane.showMessageDialog(
                    this,
                    "Employee Deleted Successfully!"
                );

                loadEmployees();

                // Clear fields
                txtID.setText("");
                txtName.setText("");
                cmbDepartment.setSelectedIndex(0);
                txtPosition.setText("");
                txtSalary.setText("");

            } else {

                JOptionPane.showMessageDialog(
                    this,
                    "Employee ID " + id + " was not found."
                );
            }
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
            this,
            "Employee ID must be a number."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Database Error:\n" + e.getMessage()
        );
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    txtID.setText("");
    txtName.setText("");
    txtPosition.setText("");
    txtSalary.setText("");
    txtSearch.setText("");

    if (cmbDepartment.getItemCount() > 0) {
        cmbDepartment.setSelectedIndex(0);
    }

    tblEmployees.clearSelection();

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      String search = txtSearch.getText().trim();

    DefaultTableModel model =
        (DefaultTableModel) tblEmployees.getModel();

    model.setRowCount(0);

    String sql =
        "SELECT [ID], [Name], [Department], [Position], [Salary] " +
        "FROM [Employees] " +
        "WHERE [Name] LIKE ? " +
        "OR [Department] LIKE ? " +
        "OR [Position] LIKE ?";

    try (Connection con = MSConnect.conn();
         PreparedStatement pst = con.prepareStatement(sql)) {

        if (con == null) {
            return;
        }

        // Access/UCanAccess wildcard
        String keyword = "%" + search + "%";

        pst.setString(1, keyword);
        pst.setString(2, keyword);
        pst.setString(3, keyword);

        try (ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getObject("ID"),
                    rs.getString("Name"),
                    rs.getString("Department"),
                    rs.getString("Position"),
                    rs.getDouble("Salary")
                });
            }
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(
                this,
                "No employee found."
            );
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Search Error:\n" + e.getMessage()
        );
    }


    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
